### ISSUE TITLE
Get live shock data during comp

### ISSUE THREAD

**Issue by P7R7M** [Georgia-Tech-Off-Road/DAQ#18]
Maybe find an alternative to the LDS's that is less prone to breakage and less intrusive on the car, like IMU's or something

**Comment by Ian-Boraks** [comment]
We got permission to run the Aux-Daq during Wisconsin

**Comment by Vishnav03** [comment]
Moved to Blocked because need to prioritize getting things working at the bare minimum for Testing Day/Comp
