### ISSUE TITLE
Design and 3D print brake light battery and radio holder

### ISSUE THREAD

**Issue by P7R7M** [Georgia-Tech-Off-Road/DAQ#2]

**Comment by Ian-Boraks** [comment]
Finished printing v1 on Jan 12

**Comment by Ian-Boraks** [comment]
V1 had a good fit, but needs to be increased in size and tabs added

**Comment by Ian-Boraks** [comment]
This will be used for https://github.com/Georgia-Tech-Off-Road/DAQ/issues/11

**Comment by Ian-Boraks** [comment]
Archived #11 as this has now merged the two. Today we added new tabs and a made the box bigger. @P7R7M  will be printing it latter in the week for a V2 test

**Comment by Ian-Boraks** [comment]
https://github.com/Georgia-Tech-Off-Road/DAQ/commit/43b6f6a713b48867f5e4790277460cfd42a0ae8f

**Comment by Ian-Boraks** [comment]
Fit on car was "ok". Need to move the holes to the other side and add a grommet system.

**Comment by Esittt** [comment]
https://github.com/Georgia-Tech-Off-Road/DAQ/commit/6d64d8a79a257bd8de2b01a2ad8e14167b328918

changed the sides of the antenna hole and the wires hole.

**Comment by Ian-Boraks** [comment]
Waiting until new car is built to do final measuring for tab spacing

**Comment by Ian-Boraks** [comment]
Plate for mounting is being manufactured
