### ISSUE TITLE
Routing Wires on Car

### ISSUE THREAD

**Issue by Vishnav03** [Georgia-Tech-Off-Road/DAQ#25]
Extend Hall effect sensor wire
Extend diff temp sensor wire
Route brake pressure sensor wire
Route brake light sensor wire
Route rotary encoder sensor wire
Route IMU sensor

**Comment by P7R7M** [comment]
once aux daq is mounted I can do all of the routing, until then the wires are at least connected , only thing missing should be belt temp sensor since i dont quite know where that goes yet, but should be easy to do on sunday
