### ISSUE TITLE
Organize powerchest w/ documentation

### ISSUE THREAD

**Issue by P7R7M** [Georgia-Tech-Off-Road/DAQ#8]

**Comment by Ian-Boraks** [comment]
@P7R7M What type of documentation are you looking for? @Esittt and myself have organized the chest.



![Image](https://user-images.githubusercontent.com/31255827/214082160-a511cdca-df03-4e5f-9209-d2394f6f0829.jpg)

**Comment by P7R7M** [comment]
@Ian-Boraks I'm thinking if we had a document just explaing the parts that go into it (both mechanically and electrically), and explanation/diagram of how everything is connected/organized. On tuesday I can look into what we have already and lyk

**Comment by Ian-Boraks** [comment]
> @Ian-Boraks I'm thinking if we had a document just explaing the parts that go into it (both mechanically and electrically), and explanation/diagram of how everything is connected/organized. On tuesday I can look into what we have already and lyk

Sounds good 👍🏻

**Comment by Ian-Boraks** [comment]
https://github.com/Georgia-Tech-Off-Road/GTORDocumentation/commit/c188721a480932202cb3e8a11490d802b5a6d029

**Comment by Ian-Boraks** [comment]
Fin
